### ISSUE TITLE
set UsePrecache to False

### ISSUE THREAD

**Issue by jeroenev** [r57zone/Harry-Potter-Settings#1]
If possible, add a way to set UsePrecache to False in the ini-files as well (or do it by default), this usually fixes all of the texture issues in the first 2 games.

**Comment by r57zone** [comment]
Hi, I will try to check it soon, also while you can use the F10 button, which resets the cache.

**Comment by jeroenev** [comment]
F10 also works, but I've not needed to use it if I have UsePrecache set to False (completed all 3 games with it, without any texture issues) 
thanks for looking into this, would be really nice if this was added :)

**Comment by r57zone** [comment]
[Updated the program](https://github.com/r57zone/Harry-Potter-Settings/releases) and added this tweak. Thanks for the suggestion.
