### ISSUE TITLE
game request

### ISSUE THREAD

**Issue by emanuelect** [r57zone/Harry-Potter-Settings#2]
hi, I wanted to ask if you could add the game A series of unfortunate event to the fix. Recently on pcgamingwiki the fov was fixed which was previously stuck at 90. Now it automatically changes by changing the resolution. But the debug mode doesn't work.

**Comment by r57zone** [comment]
Hi, through this program, you can change the FOV and it changes automatically if you select a resolution. For 16-9, 4:3, 5:4, there are correct FOVs.

**Comment by emanuelect** [comment]
Yes, but for harry potter games. I was wondering if you could add the A series of unfortunate event game to the list of games. It uses unreal engine 2 and is from 2004. The fov was recently fixed, but the debug mode is still locked.

**Comment by r57zone** [comment]
My program just changes the configs (text files), without fixing the engine, I have no idea what the problem with debug.
