### ISSUE TITLE
How to start it up

### ISSUE THREAD

**Issue by Chaleureux25** [r57zone/Harry-Potter-Settings#3]
I can't figure out how to start up your program.

**Comment by r57zone** [comment]
https://github.com/r57zone/Harry-Potter-Settings#download
https://github.com/r57zone/Harry-Potter-Settings/releases/

Program - https://github.com/r57zone/Harry-Potter-Settings/releases/download/1.0.5/Harry.Potter.Settings.1.0.5.Portable.zip
