### ISSUE TITLE
Main menu impossible to use

### ISSUE THREAD

**Issue by Arsaces1** [r57zone/Harry-Potter-Settings#5]
It doesn't work since the aspect ratio will always remain at 4:3 no matter what I pick. My resolution is 1366x768. The menu options get cut off from the screen
![hpss](https://user-images.githubusercontent.com/84804661/127966675-139ced13-3f7d-4fe7-b8cf-467c77d9d71e.png)

**Comment by r57zone** [comment]
You need to use a resolution of 1440 by 1080 or install this mod, which fixes the menu https://www.oldunreal.com/cgi-bin/yabb2/YaBB.pl?num=1524782985

**Comment by Arsaces1** [comment]
Thanks, I've already tried that mod before, but it only crashes the game with a critical error message. The chamber of secrets works fine with your patch, but its pause menu is also off-screen.

**Comment by r57zone** [comment]
Then probably need to play with a resolution of 1024 by 768. Certain cd images do not seem to work with the widescreen mod, I think the original English should work. 
Widescreen menu for HP2 https://hp-games.net/mods-cs-jagotuwidescreen-en
