### ISSUE TITLE
HP Prisoner of Azkaban - Minor Glitch

### ISSUE THREAD

**Issue by chestfindman** [r57zone/Harry-Potter-Settings#6]
Just a nitpick,

When applying tweaks to .ini files, in my case at least (could be just me), the FoV values are set in the wrong file.
For some reason the FoV adjustment gets added to "hppoa.ini" instead of "User.ini". and as a result, it has no effect.

Also, while I'm here, could I suggest expanding the FoV/Resolution pool just a little bit?
For less common ARs:

2560x1080 / 121.28
3440x1440 / 121.66

(Russian):

Программа ошибочно добавляет параметры поля обзора в неправильный файл настройки для 3-ей игры (hppia.ini) вместо (user.ini) где они должны быть.

И еще, если есть желание, можно добавить упомянутые выше разрешения и углы обзора для них (можно просто прописать в .txt с программой, легче будет менее опытным пользователям разобраться).

**Comment by r57zone** [comment]
Hi, fixed, could you check? Thank you.

Привет, поправил, не могли бы проверить? Спасибо.

https://github.com/r57zone/Harry-Potter-Settings/releases

**Comment by chestfindman** [comment]
Of course.
Just checked, everything is working properly now, thank you!
