### ISSUE TITLE
Screen too large in menu

### ISSUE THREAD

**Issue by nex86** [r57zone/Harry-Potter-Settings#9]
How do I fix the screen being too large im menus?

I can't see half of the screen even though I selected the right resolution for my monitor.

Using DX9 renderer btw

**Comment by r57zone** [comment]
Hi, you need to use a patch for the widescreen menu. Also for the first part there is a mod that adds strafeing. Check out the wiki for this game.

> Use the Unofficial Widescreen Patch
https://www.pcgamingwiki.com/wiki/Harry_Potter_and_the_Philosopher%27s_Stone
